### ISSUE TITLE
Error when running training LUT

### ISSUE THREAD

**Issue by ghost** [thatcherfreeman/log2lin-finder#1]
Installed dependencies fine.

Trying to run training lut 

  `processor.py --lut_file training_luts\zlog2_to_linear_4096.cube`

Results in;

```
Traceback (most recent call last):
  File "LOCATION\log2lin-finder-master\processor.py", line 9, in <module>
    from src.lut_parser import read_1d_lut, write_1d_lut, lut_1d_properties
  File "LOCATION\log2lin-finder-master\src\lut_parser.py", line 7, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python312\Lib\dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python312\Lib\dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python312\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python312\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'numpy.ndarray'> for field contents is not allowed: use default_factory
```

**Comment by thatcherfreeman** [comment]
hey go ahead and pull the code again. I made a update and it works for me on python 3.12 with

```
python processor.py --lut_file training_luts/zlog2_to_linear_4096.cube  --learning_rate 1e-4 --num_epochs 1000  --model_name exp_arri_function
```

Maybe raise the num epochs to 20k if you want a good fit

**Comment by ghost** [comment]
Had to downgrade to numpy 1.26.4.  Threw error with 2.0 installed.

Ran fine now. Thanks
